[package]
name = "joos-fire"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
vmm = { path = "../vmm" }
libc = "0.2.186"
vmm-sys-util = "0.15.0"
vm-memory = { version = "0.17.1", features = ["backend-mmap", "backend-bitmap"] }

[build-dependencies]
serde_json = "1.0"

[lints]
workspace = true
